### ISSUE TITLE
There's no room or any other UI component

### ISSUE THREAD

**Issue by dipaq76** [floatinghotpot/casino-server#21]
I see only the language dropdown and my own user on the right side. No other user is displayed although I logged in from 5 different computers. Further, when I click on the "games" button, nothing happens. Do I need to create the rooms somewhere before I can see the other UI elements?
![screenshot from 2017-05-16 18 42 34](https://cloud.githubusercontent.com/assets/28732060/26109947/7507b2da-3a6e-11e7-9fc1-ab41502a0f4b.png)

**Comment by floatinghotpot** [comment]
Same as #19, fixed.
