### ISSUE TITLE
A list of what is fully working and what kind of issues/bugs there are

### ISSUE THREAD

**Issue by zilveer** [floatinghotpot/casino-server#3]
Hello,
I would like to contribute to this project, but I would like to have a list where it is written what is fully working and what kind issues/problems there is (if there is any).

Is this possible?

regards

**Comment by floatinghotpot** [comment]
all info is in the source code and the readme and *.MD files, including features and TODO list, 

so far, the jinhua and holdem game rules are nearly implemented and almost working, but need more test.

i suggest:
* install and run the server, and play the features.
* git clone and read the source code and readme and doc under docs folder to understand how it works.
* propose what you can contribute, let's align action.
* fork and add your code, after test, send pull request.

**Comment by zilveer** [comment]
Yeah i know that:)
Just wanted to know if there are known bugs..
I Will test the game These days and see if i find any bugs.
