### ISSUE TITLE
Redis persistence store

### ISSUE THREAD

**Issue by zilveer** [floatinghotpot/casino-server#4]
I Am pretty new to redis, does the game store account info and player info as redis persistence store or is everything lost when the computer is shut down?

**Comment by floatinghotpot** [comment]
redis auto save data to disk in dump.rdb, so everything can be persistence, user account and data (coins, score, exp, level) is in key "user:#{uid}".

**Comment by floatinghotpot** [comment]
in redis-cli, type 'keys' to see all keys, type 'keys user:#*' to list all user record, type 'hgetall user:#uid' to see one user record.

**Comment by zilveer** [comment]
Ok thx for the reply..
May I ask why you choose redis instead of mongodb to store the account and player info?

**Comment by floatinghotpot** [comment]
here is the answer:
http://www.badrit.com/blog/2013/11/18/redis-vs-mongodb-performance#.VLPTgmSUdQ4

and a picture:
![redis_vs_mongodb](http://www.badrit.com/system/blog_assets/0000/0051/Mongo_Vs_Redis.png)

**Comment by floatinghotpot** [comment]
and here:
http://kkovacs.eu/cassandra-vs-mongodb-vs-couchdb-vs-redis

redis has pub/sub for messaging, which is a big plus, used in casino-server as message bus.

**Comment by zilveer** [comment]
Wow.. didnt know that..
Then you really have done the correct chose=)
