### ISSUE TITLE
Reference error

### ISSUE THREAD

**Issue by adrivanrex** [floatinghotpot/casino-server#7]
![f094d14124e69250479a54cdfe2e9ce9](https://cloud.githubusercontent.com/assets/2757277/7247453/3c9a5b86-e83c-11e4-94c2-fa5b54e882a6.png)

you have a mispelled error

**Comment by floatinghotpot** [comment]
it's fixed in commit 7f42931cc0936889e6c01e926a8d06baebec4ab0, please update.
