### ISSUE TITLE
card comparison description bug

### ISSUE THREAD

**Issue by G-h-o-s-t** [floatinghotpot/casino-server#9]
Then the game is over, and some one have combination of "Three of a kind", server it detect as FLUSH. But it is not flush, just free equal cards. :(

**Comment by floatinghotpot** [comment]
thanks for the bug report, will look into it.

**Comment by G-h-o-s-t** [comment]
Raymond, thank you for you good code. I am writing front side to this
casino server, then it will be done, I will share it.


пятница, 22 мая 2015 г. пользователь Raymond Xie написал:

**Comment by G-h-o-s-t** [comment]
Raymond, i'm sorry this was my bug. ))) in the poker it seems ok.

2015-05-22 11:03 GMT+03:00 Pavel Alexandrovitch <pavel@shutdown.ru>:

**Comment by floatinghotpot** [comment]
ok, thanks for the update. looking forward to seeing your front-end soon.

**Comment by zilveer** [comment]
@G-h-o-s-t did u ever develop a GUI for this?
